### ISSUE TITLE
Dist files contain references to `@nextcloud/typings` put is not declared as peer dep

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-l10n#609]
Example: https://www.runpkg.com/?@nextcloud/l10n@2.1.0/dist/registry.d.ts

Importing and building might/will generate errors in other libs if they don't use `@nextcloud/typing` themselves

Ref https://github.com/nextcloud/nextcloud-files/pull/621
cc @ChristophWurst  @susnux

**Comment by susnux** [comment]
I am still not sure if peer dependency or plain dependency is the correct way, what do you think?

**Comment by skjnldsv** [comment]
Peer is automatically installed if you import the library.
Runtime is not really fitting here too as this is for typings only :thinking:

**Comment by ChristophWurst** [comment]
Peer means it's pushed down as dependency of packages that require this package. I don't think that is necessary. The typings are a dev dep of this package.

**Comment by ChristophWurst** [comment]
Same issue with the router

```
> tsc

node_modules/@nextcloud/router/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '@nextcloud/typings'.

1 /// <reference types="@nextcloud/typings" />
                        ~~~~~~~~~~~~~~~~~~
```

**Comment by ChristophWurst** [comment]
If typings are part of `dist`, doesn't that even make them regular dependencies?

Peer dependencies might create a dependency hell. Imagine we have to packages @nextcloud/a and @nextcloud/b. @nextcloud/a depends on typings v3, @nextcloud/b uses typings v4. If they had the typings as peer dependencies, an app would not be able to install a and b because it would become impossible to satisfy both a's and b's requirements.
If the typings are dev dependencies, they do not get installed.
If the typings are regular dependencies then npm's deep hierarchy allows the parallel installation of typings in v3 and v4.

**Comment by ChristophWurst** [comment]
We also can't be the first ones to run into this. I'm sure other packages faced the same challenge.

**Comment by ChristophWurst** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies so regular dependencies it is.
